### ISSUE TITLE
PurgeCSS isn't allowing the compilation classes with prefix

### ISSUE THREAD

**Issue by vicainelli** [simonswiss/tailwind-starter#2]
Hi guys, 

I don't know why, but, when I try to use `hover:text-green` or `md:w-1/2` on any element for example, the `.css` file in `/dist/` path does not contain these prefixes.

If I put a comment on this line, it works.
https://github.com/simonswiss/tailwind-starter/blob/a8f5baa3ad0cac2ea005a7195543cfbc40222fd4/gulpfile.js#L17

Does it happen to anyone else?

**Comment by brandonhz** [comment]
I had that same exact issue and your solution seemed to work.

**Comment by simonswiss** [comment]
Thanks for pointing that out, and sorry for the long delay in my answer!

To avoid the `:` prefixed classes to be stripped out, a custom `extractor` is needed for purgeCSS.

I have updated the gulpfile to cater for that, as per the Tailwind documentation:

```javascript
// Custom extractor for purgeCSS, to avoid stripping classes with `:` prefixes
class TailwindExtractor {
  static extract(content) {
    return content.match(/[A-z0-9-:\/]+/g) || [];
  }
}
```

and then, in the CSS task:

```javascript
.pipe(
      purgecss({
        content: [paths.dist.base + "*.html"],
        extractors: [
          {
            extractor: TailwindExtractor,
            extensions: ["html", "js"]
          }
        ]
      })
```
This is now fixed as per https://github.com/simonswiss/tailwind-starter/commit/ef11c9ddd3217a2daadd910391883771282d2077
